import { Geist, Geist_Mono } from "next/font/google";
import { FaFacebookF, FaTwitter, FaInstagram, FaYoutube, FaTelegramPlane, FaWordpress, FaTripadvisor, FaMapMarkerAlt } from "react-icons/fa";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Top Bar */}
        <div className="bg-blue-900 text-white flex items-center justify-between px-6 py-2 text-sm">
          <div className="flex gap-4 items-center text-lg">
            <a href="https://twitter.com/ISKCONPune" target="_blank" rel="noopener" aria-label="Twitter"><FaTwitter /></a>
            <a href="https://facebook.com/ISKCONNVCC" target="_blank" rel="noopener" aria-label="Facebook"><FaFacebookF /></a>
            <a href="https://www.google.com/maps/place/ISKCON+NVCC+Pune/" target="_blank" rel="noopener" aria-label="Location"><FaMapMarkerAlt /></a>
            <a href="https://instagram.com/iskconnvccpune/" target="_blank" rel="noopener" aria-label="Instagram"><FaInstagram /></a>
            <a href="https://youtube.com/@ISKCONNVCCPune" target="_blank" rel="noopener" aria-label="YouTube"><FaYoutube /></a>
            <a href="https://t.me/iskconpuneofficial" target="_blank" rel="noopener" aria-label="Telegram"><FaTelegramPlane /></a>
            <a href="https://en.m.wikipedia.org/wiki/ISKCON_Temple,_Pune" target="_blank" rel="noopener" aria-label="WordPress"><FaWordpress /></a>
            <a href="https://www.tripadvisor.in/Attraction_Review-g297654-d3838598-Reviews-ISKCON_NVCC_Temple-Pune_Pune_District_Maharashtra.html" target="_blank" rel="noopener" aria-label="Tripadvisor"><FaTripadvisor /></a>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-teal-300">📞</span>
            <span>+91 7032241089</span>
          </div>
        </div>
        {/* Main Navigation */}
        <nav className="flex items-center justify-between px-6 py-4 bg-blue-50 shadow-md sticky top-0 z-10">
          <div className="flex items-center gap-4">
            <a href="/">
              <img src="/iskcon-logo.png" alt="ISKCON Logo" width={60} height={60} className="shadow-lg rounded" />
            </a>
          </div>
          <ul className="hidden md:flex gap-8 text-lg font-medium text-blue-900 items-center">
            <li><a href="/" className="hover:text-teal-600 font-semibold">Home</a></li>
            <li><a href="/about" className="hover:text-teal-600">About</a></li>
            <li><a href="/temple" className="hover:text-teal-600">Temple</a></li>
            <li><a href="/activities" className="hover:text-teal-600">Activities</a></li>
            <li><a href="/festivals" className="hover:text-teal-600">Festivals</a></li>
            <li><a href="/contact-us" className="hover:text-teal-600">Contact Us</a></li>
            <li><a href="/media" className="hover:text-teal-600">Media</a></li>
            <li><a href="/shop" className="hover:text-teal-600">Shop</a></li>
            <li><a href="/utilities" className="hover:text-teal-600">Utilities</a></li>
          </ul>
          <div className="flex items-center gap-4">
            <a href="/donate" className="border-2 border-teal-400 text-teal-600 font-semibold rounded-full px-8 py-2 hover:bg-teal-50 transition text-lg">DONATE NOW</a>
          </div>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
