import { Geist, Geist_Mono } from "next/font/google";
import { FaFacebookF, FaTwitter, FaInstagram, FaYoutube, FaTelegramPlane, FaWordpress, FaTripadvisor, FaMapMarkerAlt } from "react-icons/fa";
import Navbar from "./Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Top Bar */}
        <div className="bg-blue-900 text-white flex items-center justify-between px-6 py-2 text-sm">
          <div className="flex gap-4 items-center text-lg">
            <a href="https://twitter.com/ISKCONPune" target="_blank" rel="noopener" aria-label="Twitter"><FaTwitter /></a>
            <a href="https://facebook.com/ISKCONNVCC" target="_blank" rel="noopener" aria-label="Facebook"><FaFacebookF /></a>
            <a href="https://www.google.com/maps/place/ISKCON+NVCC+Pune/" target="_blank" rel="noopener" aria-label="Location"><FaMapMarkerAlt /></a>
            <a href="https://instagram.com/iskconnvccpune/" target="_blank" rel="noopener" aria-label="Instagram"><FaInstagram /></a>
            <a href="https://youtube.com/@ISKCONNVCCPune" target="_blank" rel="noopener" aria-label="YouTube"><FaYoutube /></a>
            <a href="https://t.me/iskconpuneofficial" target="_blank" rel="noopener" aria-label="Telegram"><FaTelegramPlane /></a>
            <a href="https://en.m.wikipedia.org/wiki/ISKCON_Temple,_Pune" target="_blank" rel="noopener" aria-label="WordPress"><FaWordpress /></a>
            <a href="https://www.tripadvisor.in/Attraction_Review-g297654-d3838598-Reviews-ISKCON_NVCC_Temple-Pune_Pune_District_Maharashtra.html" target="_blank" rel="noopener" aria-label="Tripadvisor"><FaTripadvisor /></a>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-teal-300">📞</span>
            <span>+91 7032241089</span>
          </div>
        </div>
        {/* Main Navigation */}
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
